# **exercicios ~**

In [1]:
from numpy import *
import numpy as np
import math

**exercicio 2.1 trabalhando com for**

In [2]:
x = list(range(1, 10))
y = list(range(2, 20, 2))
z = list(range(50, 5, -5))

print(f'a) inteiros menores que 10: {x}')
print(f'b) pares menores que 20: {y}')
print(f'a) multiplos de 5 menores que 50, decrescente: {z}')

a) inteiros menores que 10: [1, 2, 3, 4, 5, 6, 7, 8, 9]
b) pares menores que 20: [2, 4, 6, 8, 10, 12, 14, 16, 18]
a) multiplos de 5 menores que 50, decrescente: [50, 45, 40, 35, 30, 25, 20, 15, 10]


**exercicio 2.2 soma dos inversos**

In [3]:
k = 1
s = 0

for k in range(1, 101):
  s += 1/k

print(f's = {s:.3f}')

s = 5.187


**exercicio 2.3 criando vetores e matrizes** *

In [13]:
x = arange(0, 1, 0.01)


y_zeros = zeros([3, 3], int)

count = 1

for i in range(3):
  for j in range(3):
    y_zeros[i, j] = count
    count += 1


y_array = array([[1,2,3],[4,5,6],[7,8,9]], int)

y_load = loadtxt('matrix.txt', int)

print(f'x: {x}\n')
print(f'y_zeros: \n{y_zeros}\n')
print(f'y_array: \n{y_array}\n')
print(f'y_load: \n{y_load}\n')

x: [0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99]

y_zeros: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

y_array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

y_load: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]



**exercicio 2.4 suponha vetores a e b**

In [14]:
a = array([1, 2, 3, 4], int)
b = array([2, 4, 6, 8], int)

print(f'a) acredito que imprima 3, 3, 3, 3: {b/a+1}')
print(f'a) acredito que imprima 1, 1.33, 1.5, 1.6: {b/(a+1)}')
print(f'a) acredito que imprima 1, 0.5, 0.33, 0.25: {1/a}')

a) acredito que imprima 3, 3, 3, 3: [3. 3. 3. 3.]
a) acredito que imprima 1, 1.33, 1.5, 1.6: [1.         1.33333333 1.5        1.6       ]
a) acredito que imprima 1, 0.5, 0.33, 0.25: [1.         0.5        0.33333333 0.25      ]


**exercicio 2.5 operacoes com matrizes - parte 1**

In [15]:
A = array([[1,2,3],[4,5,6],[7,8,9]], int)
B = array([[9,8,7], [6,5,4], [3,2,1]], int)
C = dot(A,B)

print(f'{B} \n')
print(f'a) 2B:\n {2*B} \n')
print(f'b) A+B:\n {A+B} \n')
print(f'c) AB:\n {A*B} \n') # ressultado fora do esperado

print(f'usando dot para AB:\n {C} \n') # resultado esperado

[[9 8 7]
 [6 5 4]
 [3 2 1]] 

a) 2B:
 [[18 16 14]
 [12 10  8]
 [ 6  4  2]] 

b) A+B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]] 

c) AB:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]] 

usando dot para AB:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]] 



**exercicio 2.6 operacoes com matrizes - parte 2**

In [16]:
B = array([[9,8,7], [6,5,4], [3,2,1]], int)

maior = np.max(B)
menor = np.min(B)
soma = sum(B)
elements = size(B)

print(f'a) maior: {maior} e menor: {menor}\n')
print(f'b) valor medio: {soma/elements}\n')
print(f'c) matriz C:\n {sqrt(B)}\n')

a) maior: 9 e menor: 1

b) valor medio: 5.0

c) matriz C:
 [[3.         2.82842712 2.64575131]
 [2.44948974 2.23606798 2.        ]
 [1.73205081 1.41421356 1.        ]]



**exercicio 2.7 copiando vetores**

In [17]:
a = array([1,1], int)
b = a

a[0] = 2

print(f'a:\n {a} \nb:\n {b}')

# esperava que b = [1,1]

a:
 [2 1] 
b:
 [2 1]


In [18]:
a = array([1,1], int)
b = copy(a)

a[0] = 2

print(f'a:\n {a} \nb:\n {b}')

# agora b saiu como esperado

a:
 [2 1] 
b:
 [1 1]


**exercicio 2.8 fatiamento**

In [19]:
D = array([[1,2,3],[6,4,2],[3,6,9]], int)

print(f'D:\n {D}\n')

a = D[0,:]
b = D[:,1]
c = D[2, 1:3]

print(f'a) a:\n {a}\n')
print(f'b) b:\n {b}\n')
print(f'c) c:\n {c}\n')

D:
 [[1 2 3]
 [6 4 2]
 [3 6 9]]

a) a:
 [1 2 3]

b) b:
 [2 4 6]

c) c:
 [6 9]



**exercicio 2.9 fatorial**

In [20]:
def fatorial(n):
  if(n>1):
    return n*fatorial(n-1)
  else:
    return n

n = int(input('digite o numero para calcular o fatorial: ')) #4

res = fatorial(n)

print(f'\no fatorial de {n} eh: {res}')

digite o numero para calcular o fatorial:  5



o fatorial de 5 eh: 120


**exercicio 2.10 mapeando funcoes definidas pelo usuario**

In [21]:
def fatorial(n):
  if(n>1):
    return n*fatorial(n-1)
  else:
    return n

a = array([2,3,4,5], int)

b = array(list(map(fatorial, list(a))))

print(f'vetor b: {b}')

vetor b: [  2   6  24 120]


# **problemas opcionais ~**

**exercicio 2.11 media aritmetica e geometrica**

In [22]:
lst = loadtxt('values.txt', float)

media_art = sum(lst)/size(list)

media_geom = exp(sum(lst)/size(lst))

print(f'media aritmetica: {media_art:.2f} \nmedia geometrica: {media_geom:.2f}')

media aritmetica: 210.00 
media geometrica: 36315.50


**exercicio 2.12 numeros primos**

In [23]:
def primos(n):                          # funcao que verifica se é primo
  cont = 0
  for i in range(1, n+1):
    if n % i == 0:
      cont += 1

  if cont == 2:
    return True
  else:
    return False

def addFatores(n, i):                  # função que add fatores primos à lista 'fatores'
  if n%ePrimo[i] == 0:
    if n/ePrimo[i] != 1:
      fatores.append(ePrimo[i])
      n = n/ePrimo[i]
      addFatores(n, i)

    else:
      fatores.append(ePrimo[i])
      return fatores

  else:
    addFatores(n, i+1)

In [24]:
n = int(input('digite um numero: '))

ePrimo = []

for i in range(2, n+1):
  if primos(i) == True:               # se i é primo, add à lista de primos 'ePrimo'
    ePrimo.append(i)

fatores = []
i = 0
addFatores(n, i)

print(f'fatores primos: {fatores}')   # imprime a lista de fatores primos 'fatores'

digite um numero:  200


fatores primos: [2, 2, 2, 5, 5]


**exercicio 2.13 recorrência**

In [25]:
def recursao(n):
  if n == 0:
    return 1
  elif n > 0:
    x = recursao(n-1)*(4*n-2)/(n+1)
    return x

n = int(input('digite o valor de n: '))-1

print(f'valor de Cn: {recursao(n)}')

digite o valor de n:  7


valor de Cn: 132.0
